os: linux
dist: bionic

language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'

cache:
  pip: true

install:
  - pip install -r requirements.txt

before_script:
  - uvicorn --log-level error app:app & disown
  - sleep 5

script:
  - git clone https://github.com/git/git.git
  - cd git
  - git remote add local http://localhost:8000/git
  - git push local master

