name: build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Flake8
        run: |
          pip install flake8
          flake8 --statistics gitserver

      - name: Build container
        run: docker build . -t gitserver

      - name: Run container
        run: |
          docker run --rm -itd -p 8000:8000 gitserver
          sleep 5
          docker ps -a

      - name: Test container
        run: |
          git clone https://github.com/git/git.git
          cd git
          git remote add local http://localhost:8000/git
          git push local master
